SELECT [Account_Tree_Id]
      ,[Account_Tree_Code]
      ,[Account_Tree_Description]
      ,[Account_Tree_Node_Id]
      ,[Account_Tree_Node_Type]
      ,[Account_Tree_Node_Code]
      ,[Account_Tree_Node_Code_Formatted]
      ,[Account_Tree_Node_Description]
      ,[Account_Tree_Node_Indent]
      ,[Account_Tree_Node_Code_and_Description]
      ,[Account_Tree_Node_Custom_1]
      ,[Account_Tree_Node_Custom_2]
      ,[Account_Tree_Node_Custom_3]
      ,[Account_Tree_Node_Custom_4]
      ,[Account_Tree_Node_Reverse]
      ,[Account_Tree_Node_Negate]
      ,[Account_Tree_Node_Sign]
      ,[Account_Tree_Node_Total_Into_Id]
      ,[Is_Hidden]
      ,[Account_Tree_Node_Nest_Level]
      ,[GL_Account_Id]
      ,[Database_Id]
      ,[Source_Data_Through]
  FROM [DataFreedom_Client].[dbo].[df_Financial_Account_Tree_Xref]
  WHERE [Account_Tree_Code] = 'z-detailcashpl4'