SELECT TOP (1000) [Property]
      ,[Property_Name]
      ,[Date]
      ,[Period]
      ,[Book]
      ,[Person-Description]
      ,[Control]
      ,[Reference]
      ,[Currency]
      ,[Debit]
      ,[Credit]
      ,[Balance]
      ,[Net_Entry]
      ,[Remarks]
      ,[GL_Account_Id]
      ,[Account]
      ,[Account_Description]
      ,[Budget]
      ,[Ending_Balance]
      ,[Source]
      ,[DateTime_Exported]
  FROM [DataFreedom_Client].[dbo].[VDC_BI_GLDetail]
