SELECT TOP (1000) 
	   --[Agg_Incl_Flag]
    --  ,[YCO_SZN_Incl_Flag]
    --  ,[DCO_SZN_Incl_Flag]
    --  ,[All_DevCo_Incl_Flag]
    --  ,[Lease_ID]
    --  ,[Lease_Sig_Order]
       [Tenant_Name]
      --,[Ultimate_Customer_Parent]
      --,[Lease_Sig_Date]
      ,[Building]
      ,[Data_Module]
      ,[Leased_kW]
      ,[Ramped_kW]
      --,[Rent_Currency]
      --,[FX_Latest_Rate]
      --,[FX_Sign_Rate]
      --,[Initial_Rent]
      --,[Loc_Curr_Current_Rate]
      --,[USD_Current_Rate]
      --,[Mth_Base_Rent]
      --,[Annualized_Rent]
      --,[Run_Rate_Revenu]
      --,[BBNB_Revenue]
      --,[TCV_(MM_USD)]
      --,[Add_Base_Rent]
      --,[Init_Office_Base_Rent]
      --,[Curr_Office_Base_Rent]
      --,[Total_Curr_Add_Rent_(LC)]
      --,[Total_Curr_Add_Rent_(USD)]
      --,[Run-Rate_Add_Rent]
      ,[Lease_Start_Date]
      ,[Lease_End_Date]
      --,[Original_Term]
      --,[Remain_Term]
      --,[Remain_Term_(Yrs)]
      --,[Cashflow_Begin_Period]
      --,[Payment_Frequency]
      --,[Rent_Electricity]
      --,[Rent_Tax_Ins]
      --,[Annual_Escalator]
      --,[Escalator_Date]
      --,[Escalator_Frequency]
	  ,ct.YearMonth
  FROM [IMPORT].[dbo].[Datatape] dt
  left join tempdb.dbo.##calendarTbl ct on ct.Date >= dt.lease_start_date and ct.Date <= dt.lease_end_date
  where building = 'CA12'


--select top 100 * from tempdb.dbo.##calendarTbl