SELECT TOP (1000) [Entity]
      ,[Campus]
      ,[Building]
      ,[Customer]
      ,[Space]
      ,[PH]
      ,[Termination]
      ,[Currency]
      ,[Lease_Signature]
      ,[Commencement]
      ,[Maturity]
      ,[YearMonth]
      ,[Lease_Term]
      ,[Leased_kW]
      ,[StartRateLocal]
      ,[Min_TCV_Local]
      ,[TCV_Local]
      ,[FX_Rate]
      ,[Start_Rate_USD]
      ,[Avg_Rate]
      ,[GAAP_Rate_USD]
      ,[Escalator]
      ,[TCV_Guaranteed_USD_MM]
      ,[TCV_MM]
  FROM [dbo].[LeaseMatrix]
  WHERE [Building] = 'AZ14'